name = "cv-chat-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# Environment variables (set GROQ_API_KEY via wrangler secret)
[env.production]
name = "cv-chat-api"

[env.development]
name = "cv-chat-api-dev"

# Routes for custom domain (optional)
# routes = [
#   { pattern = "your-domain.com/api/*", zone_name = "your-domain.com" }
# ]